spring.application.name=pf

## DB無しテスト起動の場合ON
##spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
## Sprint Security無効化の場合ON 
##spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

spring.datasource.url=jdbc:mysql://localhost:3306/ftwebdb
spring.datasource.username=ftweb
spring.datasource.password=ftweb
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
